### PR TITLE
PIN-60-theming Add initial theming and apply to nav bar + profile

### PR DESCRIPTION
**Pull request by BPete21001**
I went in and added common colors that I think will be reused throughout the app. Then I applied these to the existing navigation bar and profile sections to display the scenarios for which each color would be used.

Some colors have yet to be used but I anticipate future use, and some seem redundant now but will likely be nice to have as complexity grows. Things can always be added/deleted, but I like this as a start. 

I also didn't use the built-in "Theme" package. It seems a bit more complicated and the current implementation gives us more control over things. That can definitely be explored but I think manually adding colors to new components should be fine.

### CODE REVIEW

**Comment by mxj220** [comment]
I think this suits our needs without being complicated. If possible, it would be good to add support for dark mode too

**Review by mxj220 — APPROVED** [review]

**Comment by ckleinhans** [comment]
Could we remove the light mode switch on the map button for now? As long as the app uses the system settings I think that is sufficient. If we implement a light/dark mode switch I think it could be positioned on the right side of the app bar at the top of the screen.

**Comment by ckleinhans** [comment]
Also, the top icon bar above the nav bar still appears purple on my phone in both light and dark mode. Is there a way to switch that to match the app?

**Comment by BPete21001** [comment]
> Also, the top icon bar above the nav bar still appears purple on my phone in both light and dark mode. Is there a way to switch that to match the app?

I need to look into this further. It wasn't as obvious as all of the other theme changes but I'm sure there's a way to make that work.

**Comment by mxj220** [comment]
Are we even planning on keeping that top bar that only says Pinpoint? I don't think it serves any purpose and is kind of ugly to me. This may be a good time to remove it

**Comment by BPete21001** [comment]
That strip above the top bar should match the theme now. There are a few pre-defined theme attributes that control standard things (such as "colorPrimaryVariant" controlling the space above the top bar), so it's definitely good that we're utilizing that now.

**Review by mxj220 — APPROVED** [review]
Lookin good

**Pull request merged**
